# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayersFromField
                                 A QGIS plugin
 Field-Based Layer Creator: A versatile QGIS plugin that generates new layers based on field categories from any vector layer, regardless of its geometry or use.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-03
        copyright            : (C) 2024 by Sebastian Mejia Rios
        email                : sebastianmr6@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayersFromField class from file LayersFromField.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_creator import LayersFromField
    return LayersFromField(iface)
